//Admin
export const ADD_ROOM = "ADD_ROOM"
export const REMOVE_ROOM = "REMOVE_ROOM"
export const ADD_POWERUSER_RIGHTS = "ADD_POWERUSER_RIGHTS"

//Reservations
export const FETCH_ALL_RESERVATIONS = "FETCH_ALL_RESERVATIONS"
export const ADD_RESERVATION = "ADD_RESERVATION"
export const UPDATE_RESERVATION = "UPDATE_RESERVATION"
export const DELETE_RESERVATION = "DELETE_RESERVATION"


//Errors and loadings
export const CLEAR_ERROR = "CLEAR_ERROR"
export const SET_ERROR = "SET_ERROR"
export const START_LOADING = "START_LOADING"
export const STOP_LOADING = "STOP_LOADING"